import { useState } from 'react';
import { createFileRoute } from '@tanstack/react-router';
import { Check, Copy, Trash2, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { usePlan } from '@/planpulse/store';
import { Avatar } from '@/planpulse/ui';
export const Route=createFileRoute('/settings')({head:()=>({meta:[{title:'Team Settings — PlanPulse'},{name:'description',content:'Manage your PlanPulse team and weekly working capacity.'},{property:'og:title',content:'Team Settings — PlanPulse'},{property:'og:description',content:'Manage your PlanPulse team and weekly working capacity.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Settings});
function Settings(){const {members,setMembers,setTasks}=usePlan();const [remove,setRemove]=useState<string|null>(null);const [copied,setCopied]=useState(false);const link=typeof window==='undefined'?'https://planpulse.app/invite/demo':`${window.location.origin}/auth`;return <main className="mx-auto max-w-4xl px-4 py-10 md:px-8"><span className="label">Workspace / Preferences</span><h1 className="mt-3 text-3xl font-semibold">Team settings</h1><p className="mt-2 text-sm text-muted-foreground">Weekly capacity shapes your project’s risk score.</p><div className="mt-10 flex items-center gap-2 border-b border-border pb-4"><Users size={16}/><h2 className="text-sm font-semibold">Members</h2><span className="number ml-auto text-xs text-faint">{members.length} people</span></div><div className="divide-y divide-border">{members.map(m=><div key={m.id} className="flex items-center gap-3 py-4"><Avatar name={m.name}/><div className="min-w-0 flex-1"><div className="text-sm font-medium">{m.name}</div><div className="text-xs text-muted-foreground">{m.role}</div></div><label className="flex items-center gap-2 text-xs text-muted-foreground"><span className="hidden sm:inline">Capacity / week</span><Input type="number" min="1" aria-label={`${m.name} weekly capacity`} className="number w-20" value={m.capacity_hours} onChange={e=>setMembers(prev=>prev.map(x=>x.id===m.id?{...x,capacity_hours:Math.max(1,Number(e.target.value))}:x))}/><span>h</span></label><Button variant="ghost" size="icon" aria-label={`Remove ${m.name}`} onClick={()=>setRemove(m.id)}><Trash2 className="text-muted-foreground"/></Button></div>)}</div><div className="mt-12 border-t border-border pt-6"><h2 className="text-sm font-semibold">Invite teammates</h2><p className="mt-2 text-xs text-muted-foreground">Share this link to invite someone to your workspace.</p><div className="mt-4 flex gap-2"><Input readOnly value={link} aria-label="Invite link"/><Button variant="outline" onClick={async()=>{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),2000)}}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy'}</Button></div></div><Dialog open={!!remove} onOpenChange={o=>{if(!o)setRemove(null)}}><DialogContent className="bg-card shadow-none"><DialogHeader><DialogTitle>Remove member?</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Their tasks will become unassigned.</p><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setRemove(null)}>Cancel</Button><Button variant="destructive" onClick={()=>{setMembers(prev=>prev.filter(m=>m.id!==remove));setTasks(prev=>prev.map(t=>t.assignee_member_id===remove?{...t,assignee_member_id:''}:t));setRemove(null)}}>Remove member</Button></div></DialogContent></Dialog></main>}
