import { useEffect, useMemo, useState } from 'react';
import { useNavigate, Link } from '@tanstack/react-router';
import { DndContext, PointerSensor, KeyboardSensor, useSensor, useSensors, useDraggable, useDroppable, type DragEndEvent } from '@dnd-kit/core';
import { AnimatePresence, motion } from 'framer-motion';
import { differenceInCalendarDays } from 'date-fns';
import { Activity, ArrowRight, ChevronDown, ChevronUp, Command, Plus, Radar, RotateCcw, Settings2, Sparkles, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { usePlan } from './store';
import { dateFromNow, daysInStatus, makeReplan, memberName, projectHealth, riskBand, riskReason, statuses, taskRisk, type Status, type Task, type PlanChange } from './data';
import { Avatar, formatDate, HealthDial, NumberText, Score } from './ui';
import { TaskDialog } from './task-dialog';

function TaskCard({task,tasks,onOpen,flash}:{task:Task;tasks:Task[];onOpen:()=>void;flash:boolean}){
  const {members}=usePlan(); const score=taskRisk(task,tasks,members); const name=memberName(task.assignee_member_id,members); const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:task.id});
  return <motion.div layout transition={{duration:.42,ease:[.2,.8,.2,1]}} ref={setNodeRef} id={`task-${task.id}`} className={`risk-${riskBand(score)} risk-border panel relative min-h-[112px] p-3 transition-colors ${flash?'flash-task':''} ${score>=85?'risk-pulse':''} ${isDragging?'z-50 opacity-60':''}`} style={{transform:transform?`translate3d(${transform.x}px, ${transform.y}px, 0)`:undefined}}>
    <div className="flex items-start justify-between gap-2"><Button variant="ghost" className="h-auto min-w-0 justify-start whitespace-normal p-0 text-left text-[13px] font-semibold leading-snug text-foreground hover:bg-transparent" onClick={onOpen}>{task.title}</Button><Score score={score}/></div>
    <div className="mt-4 flex items-center gap-2 text-[10px] font-semibold uppercase text-muted-foreground"><Avatar name={name} small/><span className="number">{task.estimate_hours}h</span><span className="text-faint">·</span><span className="number">{formatDate(task.due_date)}</span>{daysInStatus(task)>6&&task.status!=='todo'&&task.status!=='done'&&<span className="ml-auto truncate text-risk-high">{daysInStatus(task)}d in progress</span>}</div>
    {score>=65&&<p className="mt-2 truncate text-[11px] text-muted-foreground">{riskReason(task,tasks,members)}</p>}
    <div {...attributes} {...listeners} role="button" tabIndex={0} aria-label={`Drag ${task.title}`} className="absolute inset-x-0 bottom-0 h-2 cursor-grab active:cursor-grabbing"/>
  </motion.div>
}
function Column({status,tasks,onOpen,flash}:{status:Status;tasks:Task[];onOpen:(t:Task)=>void;flash:string|null}){
  const {setNodeRef,isOver}=useDroppable({id:status}); const config=statuses.find(s=>s.id===status);
  return <div ref={setNodeRef} className={`min-w-[190px] flex-1 rounded-md border border-border bg-secondary/40 p-2.5 transition-colors ${isOver?'bg-secondary':''}`}><div className="mb-3 flex h-8 items-center justify-between px-1.5"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${status==='blocked'?'bg-risk-high':status==='done'?'bg-risk-none':status==='in_progress'?'bg-risk-med':'bg-faint'}`}/><span className="label text-foreground">{config?.label}</span></div><span className="number text-[11px] text-muted-foreground">{tasks.length.toString().padStart(2,'0')}</span></div><div className="min-h-[150px] space-y-2">{tasks.sort((a,b)=>a.order_index-b.order_index).map(t=><TaskCard key={t.id} task={t} tasks={tasksAllHolder.current} onOpen={()=>onOpen(t)} flash={flash===t.id}/>)}</div></div>
}
// Kept current for column rendering so dependency and overload scores include all statuses.
const tasksAllHolder:{current:Task[]}={current:[]};
function RiskPanel({tasks,onFocus,onReplan,loading,compact=false}:{tasks:Task[];onFocus:(id:string)=>void;onReplan:()=>void;loading:boolean;compact?:boolean}) {
  const {members,projects}=usePlan();const health=projectHealth(tasks,members);const ranked=tasks.filter(t=>t.status!=='done').map(t=>({t,score:taskRisk(t,tasks,members)})).sort((a,b)=>b.score-a.score).slice(0,5);
  const blocked=tasks.filter(t=>t.status==='blocked').length;const daysLeft=differenceInCalendarDays(new Date((projects[0]?.target_date||dateFromNow(8))+'T12:00:00'),new Date());
  const loads=members.map(m=>({...m,load:tasks.filter(t=>t.assignee_member_id===m.id&&t.status!=='done').reduce((sum,t)=>sum+t.estimate_hours,0)}));const over=loads.find(m=>m.load>m.capacity_hours);
  return <div className={`flex h-full flex-col ${compact?'px-4 pb-6':'px-5 pb-5'}`}><div className="border-b border-border py-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><Radar className="size-4 text-risk-med"/><h2 className="text-sm font-semibold">Risk Radar</h2></div><span className="flex items-center gap-1.5 text-[10px] font-bold uppercase text-risk-none"><span className="size-1.5 rounded-full bg-risk-none"/>Live</span></div><HealthDial health={health} large/><div className="mt-3 grid grid-cols-3 gap-1.5">{[[String(blocked),'blocked'],[over?.name.split(' ')[0]||'None','overloaded'],[String(daysLeft),'days left']].map(([num,label])=><div key={label} className="rounded-sm border border-border bg-secondary p-2 text-center"><span className="number block text-xs font-semibold text-foreground">{num}</span><span className="mt-1 block truncate text-[9px] uppercase text-muted-foreground">{label}</span></div>)}</div></div>
    <div className="border-b border-border py-5"><div className="mb-3 flex items-center justify-between"><h3 className="label text-foreground">Biggest risks</h3><span className="number text-[10px] text-muted-foreground">TOP 05</span></div><div className="space-y-1">{ranked.map(({t,score},i)=><Button variant="ghost" key={t.id} className="h-auto w-full justify-start gap-2.5 rounded-sm px-1.5 py-2 text-left hover:bg-secondary" onClick={()=>onFocus(t.id)}><span className="number w-4 shrink-0 text-[10px] text-faint">0{i+1}</span><Score score={score}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium text-foreground">{t.title}</span><span className="block truncate text-[10px] font-normal text-muted-foreground">{riskReason(t,tasks,members)}</span></span><Avatar name={memberName(t.assignee_member_id,members)} small/></Button>)}</div></div>
    <div className="py-5"><h3 className="label mb-4 text-foreground">Team load <span className="ml-1 text-faint">/ this week</span></h3><div className="space-y-3.5">{loads.map(m=><div key={m.id}><div className="mb-1.5 flex justify-between text-[11px]"><span className="text-muted-foreground">{m.name.split(' ')[0]}</span><span className={`number ${m.load>m.capacity_hours?'text-risk-high':'text-muted-foreground'}`}>{m.load}h <span className="text-faint">/ {m.capacity_hours}h</span></span></div><div className="relative h-1.5 w-full rounded-full border border-border-strong bg-secondary"><div className={`h-full rounded-full ${m.load>m.capacity_hours?'bg-risk-high':'bg-muted-foreground'}`} style={{width:`${Math.min(100,m.load/Math.max(1,m.capacity_hours)*100)}%`}}/><span className="absolute -top-1 right-0 h-3.5 w-px bg-foreground/60"/></div></div>)}</div></div>
    <div className="mt-auto pt-3"><Button className="h-11 w-full bg-primary font-semibold shadow-none hover:bg-primary/90" onClick={onReplan} disabled={loading}><Sparkles/> {loading?`Analysing ${tasks.length} tasks…`:'Replan the week'} <ArrowRight className="ml-auto"/></Button><p className="mt-2 text-center text-[10px] text-faint">Rebalance workload and deadlines</p></div>
  </div>
}
export function BoardPage(){
  const {tasks,setTasks,members,projects}=usePlan();tasksAllHolder.current=tasks;const [selected,setSelected]=useState<Task|null>(null);const [radarOpen,setRadarOpen]=useState(true);const [mobileRadar,setMobileRadar]=useState(false);const [flash,setFlash]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [proposal,setProposal]=useState<{tasks:Task[];changes:PlanChange[]}|null>(null);const [shortcuts,setShortcuts]=useState(false);const [undo,setUndo]=useState<Task[]|null>(null);const navigate=useNavigate();const health=projectHealth(tasks,members);const after=proposal?projectHealth(proposal.tasks,members):health;
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:5}}),useSensor(KeyboardSensor));
  const focus=(id:string)=>{setMobileRadar(false);setRadarOpen(true);setTimeout(()=>{document.getElementById(`task-${id}`)?.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});setFlash(id);setTimeout(()=>setFlash(null),1500)},200)};
  const replan=()=>{setLoading(true);setTimeout(()=>{setProposal(makeReplan(tasks,members));setLoading(false);setMobileRadar(false)},1400)};
  useEffect(()=>{function key(e:KeyboardEvent){if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName))return;if(e.key==='\\'){e.preventDefault();setRadarOpen(v=>!v)}if(e.key.toLowerCase()==='r'){e.preventDefault();replan()}if(e.key==='?'){e.preventDefault();setShortcuts(true)}if(e.key.toLowerCase()==='n'){e.preventDefault();setSelected({id:`new-${Date.now()}`,title:'New task',description:'',status:'todo',priority:'medium',assignee_member_id:'',estimate_hours:4,due_date:dateFromNow(7),status_changed_at:new Date().toISOString(),dependencies:[],order_index:tasks.filter(t=>t.status==='todo').length})}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[tasks,members]);
  useEffect(()=>{if(!undo)return;const timer=setTimeout(()=>setUndo(null),8000);return()=>clearTimeout(timer)},[undo]);
  function dragEnd(e:DragEndEvent){const id=String(e.active.id);const over=String(e.over?.id||'');if(!over)return;setTasks(prev=>prev.map(t=>t.id===id?{...t,status:statuses.some(s=>s.id===over)?over as Status:t.status,status_changed_at:statuses.some(s=>s.id===over)&&over!==t.status?new Date().toISOString():t.status_changed_at}:t))}
  const save=(t:Task)=>setTasks(prev=>prev.some(x=>x.id===t.id)?prev.map(x=>x.id===t.id?t:x):[...prev,t]);
  return <div className="flex min-h-[calc(100vh-56px)] flex-col"><div className="flex items-center justify-between gap-3 border-b border-border px-4 py-5 md:px-6"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase text-faint"><Link to="/" className="hover:text-foreground">Projects</Link><span>/</span><span className="text-muted-foreground">{projects[0]?.name||'Demo'}</span></div><h1 className="text-xl font-semibold md:text-2xl">Delivery board</h1><p className="mt-1 text-xs text-muted-foreground">{tasks.filter(t=>t.status!=='done').length} active tasks <span className="mx-1.5 text-faint">·</span> Target {formatDate(projects[0]?.target_date||dateFromNow(8))}</p></div><div className="flex shrink-0 items-center gap-2"><span className={`risk-${riskBand(100-health)} hidden items-center gap-1.5 rounded-sm border border-border bg-card px-3 py-2 text-xs sm:flex`}><span className="size-1.5 rounded-full risk-fill"/><span className="text-muted-foreground">Health</span><NumberText value={health} className="risk-text font-bold"/></span><Button variant="outline" size="icon" aria-label="Toggle Risk Radar" title="Toggle Risk Radar (\\)" onClick={()=>{if(window.innerWidth<1024)setMobileRadar(true);else setRadarOpen(v=>!v)}}><Radar/></Button><Button size="sm" onClick={()=>setSelected({id:`new-${Date.now()}`,title:'New task',description:'',status:'todo',priority:'medium',assignee_member_id:'',estimate_hours:4,due_date:dateFromNow(7),status_changed_at:new Date().toISOString(),dependencies:[],order_index:tasks.length})}><Plus/> <span className="hidden sm:inline">New task</span></Button></div></div>
  <div className="flex min-h-0 flex-1"><main className="min-w-0 flex-1 overflow-x-auto p-4 md:p-6 scrollbar-thin"><div className="mb-4 flex items-center justify-between"><span className="label">Board overview <span className="ml-2 number text-faint">/ 04 stages</span></span><span className="hidden text-[11px] text-faint sm:block">Drag tasks to change status</span></div><DndContext sensors={sensors} onDragEnd={dragEnd}><div className="flex min-w-[800px] gap-2">{statuses.map(s=><Column key={s.id} status={s.id} tasks={tasks.filter(t=>t.status===s.id)} onOpen={setSelected} flash={flash}/>)}</div></DndContext></main>{radarOpen&&<aside className="hidden w-[360px] shrink-0 border-l border-border bg-card lg:block"><RiskPanel tasks={tasks} onFocus={focus} onReplan={replan} loading={loading}/></aside>}</div>
  <div className="fixed bottom-4 right-4 z-20 lg:hidden"><Button className="shadow-none" onClick={()=>setMobileRadar(true)}><Radar/> Risk Radar <span className="number ml-2 border-l border-primary-foreground/30 pl-2">{health}</span></Button></div>
  <Dialog open={mobileRadar} onOpenChange={setMobileRadar}><DialogContent className="bottom-0 left-0 top-auto max-h-[85vh] w-full max-w-none translate-x-0 translate-y-0 overflow-y-auto rounded-t-md border-b-0 bg-card p-0 shadow-none sm:left-[50%] sm:max-w-lg sm:translate-x-[-50%]"><DialogHeader className="sr-only"><DialogTitle>Risk Radar</DialogTitle></DialogHeader><RiskPanel tasks={tasks} onFocus={focus} onReplan={replan} loading={loading} compact/></DialogContent></Dialog>
  <TaskDialog task={selected} tasks={tasks} members={members} onSave={save} onDelete={id=>setTasks(prev=>prev.filter(t=>t.id!==id))} onClose={()=>setSelected(null)}/>
  <Dialog open={!!proposal} onOpenChange={o=>{if(!o)setProposal(null)}}><DialogContent className="max-h-[90vh] max-w-[640px] overflow-y-auto bg-card shadow-none sm:rounded-md"><DialogHeader><span className="label mb-2 flex items-center gap-2 text-risk-none"><Sparkles size={14}/> Proposed plan</span><DialogTitle className="text-xl">Replan the week</DialogTitle></DialogHeader>{proposal&&<div><div className="my-5 flex items-center justify-center gap-6 rounded-md border border-border bg-background py-5"><div className="text-center"><div className="number text-4xl font-semibold text-risk-high">{health}</div><div className="label mt-1">Current health</div></div><ArrowRight className="text-faint"/><div className="text-center"><div className="number text-4xl font-semibold text-risk-none">{after}</div><div className="label mt-1">Projected health</div></div></div>{(['reassigned','rescheduled'] as const).map(type=><div key={type} className="mb-5"><h3 className="label mb-3 border-b border-border pb-2 text-foreground">{type==='reassigned'?'Reassigned':'Rescheduled'} <span className="number ml-2 text-faint">{proposal.changes.filter(c=>c.type===type).length}</span></h3><div className="space-y-3">{proposal.changes.filter(c=>c.type===type).map((c,i)=><p key={i} className="text-sm leading-relaxed"><span className="font-semibold">{tasks.find(t=>t.id===c.taskId)?.title}</span> {type==='reassigned'?`moved from ${c.from} to ${c.to}`:`due date moved from ${formatDate(c.from)} to ${formatDate(c.to)}`}<span className="mt-0.5 block text-xs text-muted-foreground">{c.reason}</span></p>)}</div></div>)}{!proposal.changes.length&&<p className="my-6 text-sm text-muted-foreground">Your plan is already balanced. No changes suggested.</p>}<div className="flex justify-end gap-2 border-t border-border pt-4"><Button variant="outline" onClick={()=>setProposal(null)}>Discard</Button><Button disabled={!proposal.changes.length} onClick={()=>{setUndo(tasks);setTasks(proposal.tasks);setProposal(null)}}>Apply plan <ArrowRight/></Button></div></div>}</DialogContent></Dialog>
  <Dialog open={shortcuts} onOpenChange={setShortcuts}><DialogContent className="max-w-sm bg-card shadow-none"><DialogHeader><DialogTitle>Keyboard shortcuts</DialogTitle></DialogHeader>{[['N','New task'],['R','Replan the week'],['\\','Toggle Risk Radar'],['?','Keyboard shortcuts']].map(([key,label])=><div key={key} className="flex items-center justify-between border-b border-border py-2 text-sm"><span>{label}</span><kbd className="number rounded-sm border border-border bg-secondary px-2 py-1 text-xs">{key}</kbd></div>)}</DialogContent></Dialog>
  {undo&&<div className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-4 rounded-md border border-border bg-secondary px-4 py-3 text-xs shadow-none">Replan applied.<Button variant="ghost" size="sm" onClick={()=>{setTasks(undo);setUndo(null)}}><RotateCcw/> Undo</Button><Button variant="ghost" size="icon" aria-label="Dismiss" className="size-6" onClick={()=>setUndo(null)}><X/></Button></div>}
  </div>
}
