import { useEffect, useState } from 'react';
import { Trash2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { riskBreakdown, statuses, taskRisk, type Task, type Member, type Status, type Priority } from './data';
import { Score } from './ui';
const priorities:Priority[]=['low','medium','high','critical'];
export function TaskDialog({task,tasks,members,onSave,onDelete,onClose}:{task:Task|null;tasks:Task[];members:Member[];onSave:(t:Task)=>void;onDelete:(id:string)=>void;onClose:()=>void}) {
  const [draft,setDraft]=useState<Task|null>(task); const [search,setSearch]=useState(''); const [confirm,setConfirm]=useState(false);
  useEffect(()=>{setDraft(task);setConfirm(false)},[task]);
  const edit=(patch:Partial<Task>)=>setDraft(d=>d?{...d,...patch}:d);
  const close=()=>{if(draft)onSave(draft);onClose()};
  const breakdown=draft?riskBreakdown(draft,tasks.map(t=>t.id===draft.id?draft:t),members):null;
  return <Dialog open={!!task} onOpenChange={open=>{if(!open)close()}}><DialogContent className="max-h-[90vh] max-w-[600px] overflow-y-auto bg-card p-6 shadow-none sm:rounded-md"><DialogHeader><DialogTitle>Task details</DialogTitle></DialogHeader>{draft&&<div className="space-y-5">
    <div><label className="label mb-2 block" htmlFor="task-title">Title</label><Input id="task-title" value={draft.title} onChange={e=>edit({title:e.target.value})}/></div>
    <div><label className="label mb-2 block" htmlFor="task-desc">Description</label><textarea id="task-desc" className="min-h-20 w-full rounded-md border border-input bg-background p-3 text-sm outline-none focus:ring-1 focus:ring-ring" value={draft.description} onChange={e=>edit({description:e.target.value})} placeholder="Add context for the team..."/></div>
    <div className="grid grid-cols-2 gap-4"><div><label className="label mb-2 block">Status</label><Select value={draft.status} onValueChange={(v:Status)=>edit({status:v,status_changed_at:new Date().toISOString()})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem value={s.id} key={s.id}>{s.label}</SelectItem>)}</SelectContent></Select></div><div><label className="label mb-2 block">Priority</label><Select value={draft.priority} onValueChange={(v:Priority)=>edit({priority:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{priorities.map(p=><SelectItem value={p} key={p}>{p.charAt(0).toUpperCase()+p.slice(1)}</SelectItem>)}</SelectContent></Select></div>
    <div><label className="label mb-2 block">Assignee</label><Select value={draft.assignee_member_id||'unassigned'} onValueChange={v=>edit({assignee_member_id:v==='unassigned'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unassigned">Unassigned</SelectItem>{members.map(m=><SelectItem value={m.id} key={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></div><div><label className="label mb-2 block" htmlFor="task-estimate">Estimate · hours</label><Input id="task-estimate" type="number" min="1" value={draft.estimate_hours} onChange={e=>edit({estimate_hours:Number(e.target.value)})}/></div>
    <div className="col-span-2"><label className="label mb-2 block" htmlFor="task-date">Due date</label><Input id="task-date" type="date" value={draft.due_date} onChange={e=>edit({due_date:e.target.value})}/></div></div>
    <div><label className="label mb-2 block" htmlFor="dependency-search">Dependencies</label><div className="mb-2 flex flex-wrap gap-2">{draft.dependencies.map(id=>{const dep=tasks.find(t=>t.id===id);return dep?<span key={id} className="inline-flex items-center gap-1 rounded-sm border border-border bg-secondary px-2 py-1 text-xs">{dep.title}<Button type="button" variant="ghost" size="icon" className="size-4" aria-label={`Remove ${dep.title}`} onClick={()=>edit({dependencies:draft.dependencies.filter(d=>d!==id)})}><X size={12}/></Button></span>:null})}</div><Input id="dependency-search" placeholder="Search tasks to add..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<div className="mt-1 max-h-32 overflow-y-auto rounded-md border border-border bg-background">{tasks.filter(t=>t.id!==draft.id&&!draft.dependencies.includes(t.id)&&t.title.toLowerCase().includes(search.toLowerCase())).map(t=><Button variant="ghost" key={t.id} className="h-8 w-full justify-start rounded-none text-xs" onClick={()=>{edit({dependencies:[...draft.dependencies,t.id]});setSearch('')}}>{t.title}</Button>)}</div>}</div>
    <div className="border-t border-border pt-4"><div className="mb-4 flex items-center justify-between"><h3 className="label">Risk breakdown</h3><Score score={taskRisk(draft,tasks.map(t=>t.id===draft.id?draft:t),members)}/></div><div className="space-y-3">{breakdown&&Object.entries(breakdown).map(([name,value])=><div key={name} className="grid grid-cols-[110px_1fr_28px] items-center gap-3"><span className="text-xs capitalize text-muted-foreground">{name.replace('_',' ')}</span><span className="h-1.5 rounded-full bg-secondary"><span className="block h-full rounded-full bg-risk-high" style={{width:`${Math.min(100,value)}%`}}/></span><span className="number text-right text-xs text-muted-foreground">{Math.round(value)}</span></div>)}</div></div>
    <div className="flex items-center justify-between border-t border-border pt-4">{confirm?<div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">Delete this task?</span><Button variant="destructive" size="sm" onClick={()=>{onDelete(draft.id);onClose()}}>Delete</Button><Button variant="ghost" size="sm" onClick={()=>setConfirm(false)}>Cancel</Button></div>:<Button variant="ghost" size="sm" className="text-destructive" onClick={()=>setConfirm(true)}><Trash2/> Delete</Button>}<Button onClick={close}>Save changes</Button></div>
  </div>}</DialogContent></Dialog>;
}
