import { useEffect, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { format, parseISO } from 'date-fns';
import { initials, riskBand } from './data';
export function Avatar({name,small=false}:{name:string;small?:boolean}) {return <span title={name} className={`inline-flex shrink-0 items-center justify-center rounded-full border border-border bg-secondary font-bold text-muted-foreground ${small?'size-6 text-[9px]':'size-8 text-[10px]'}`}>{initials(name)}</span>}
export function NumberText({value,className=''}:{value:number;className?:string}) {const [shown,setShown]=useState(value);const reduce=useReducedMotion();useEffect(()=>{if(reduce){setShown(value);return}let id=0;const start=performance.now();const from=shown;const run=(now:number)=>{let p=Math.min(1,(now-start)/1200);p=1-Math.pow(1-p,3);setShown(Math.round(from+(value-from)*p));if(p<1)id=requestAnimationFrame(run)};id=requestAnimationFrame(run);return()=>cancelAnimationFrame(id)},[value,reduce]);return <span className={`number ${className}`}>{shown}</span>}
export function HealthDial({health,large=false}:{health:number;large?:boolean}){const reduce=useReducedMotion();const band=riskBand(100-health);return <div className={`risk-${band} relative mx-auto w-[140px] ${large?'h-[104px]':'h-[92px]'}`}><svg viewBox="0 0 140 80" className="w-[140px] overflow-visible" aria-hidden="true"><path d="M 10 70 A 60 60 0 0 1 130 70" fill="none" stroke="var(--border-strong)" strokeWidth="10" strokeLinecap="round"/><motion.path d="M 10 70 A 60 60 0 0 1 130 70" fill="none" className="risk-stroke" strokeWidth="10" strokeLinecap="round" strokeDasharray="188.5" initial={false} animate={{strokeDashoffset:188.5*(1-health/100)}} transition={{duration:reduce?0:1.2,ease:'easeOut'}}/></svg><div className="absolute inset-x-0 top-[38px] text-center"><NumberText value={health} className="text-[34px] leading-none font-semibold text-foreground"/><span className="block pt-1 text-[10px] font-semibold uppercase text-muted-foreground">Health score</span></div></div>}
export function formatDate(date:string){try{return format(parseISO(date),'MMM d')}catch{return date}}
export function Score({score}:{score:number}){return <span className={`risk-${riskBand(score)} number inline-flex min-w-8 items-center justify-center rounded-sm border border-border bg-secondary px-1.5 py-1 text-[10px] font-semibold risk-text`}>{score}</span>}
